name: snapcraft_release

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_on_snapcraft:
    name: ðŸ¤– Build Snap and Publish to Snap Store
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: ðŸ“š Checks-out repository
        uses: actions/checkout@v3

      - name: ðŸ“¦ Build Snap
        uses: snapcore/action-build@v1.1.2
        id: snapcraft
        with:
          path: linux/snap

      - name: ðŸš€ Publish to Snap Store
        uses: snapcore/action-publish@v1.1.1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge